pollination_site_1_2: [0.55, 0]
pollination_site_3_4: [1.1, 0]
pollination_site_5_6: [1.65, 0]
A2: [2.2, 0]
B2: [2.2, 0.8]
pollination_site_7: [1.65, 0.8]
pollination_site_8: [1.1, 0.8]
pollination_site_9: [0.55, 0.8]
B1: [0, 0.8]
C1: [0, 1.6]
pollination_10_11: [0.275, 1.6]