joint1_vision_patrol_1: 126
joint2_vision_patrol_1: 115
joint3_vision_patrol_1: 124
joint4_vision_patrol_1: 96

joint1_vision_patrol_2: 126
joint2_vision_patrol_2: 115
joint3_vision_patrol_2: 124
joint4_vision_patrol_2: 96

# A 区
# '_a_left' 指的是车在 A 区行驶时车的左边
# '_a_left' 指的是车在 A 区行驶时车的左边
joint1_a_left: 68
joint2_a_left: 79
joint3_a_left: 95
joint4_a_left: 75
joint1_a_right: 157
joint2_a_right: 80
joint3_a_right: 65
joint4_a_right: 85

joint2_a_1: 120
joint3_a_1: 90
joint4_a_1: 110

joint2_a_2: 117
joint3_a_2: 80
joint4_a_2: 107

joint2_a_3: 115
joint3_a_3: 64
joint4_a_3: 116

# 过渡点
joint2_middle: 110
joint3_middle: 105
joint4_middle: 90

# B 区
# '_b_front' 指的是车在 A 区行驶时车的前方
# '_b_back' 指的是车在 A 区行驶时车的后方
joint1_moving: 111
joint2_moving: 79
joint3_moving: 70
joint4_moving: 75
# -----------------------
joint1_b_left_front_pre: 97
joint2_b_left_front_pre: 111
joint3_b_left_front_pre: 124
joint4_b_left_front_pre: 99

joint1_b_middle_front_pre: 111
joint2_b_middle_front_pre: 107
joint3_b_middle_front_pre: 124
joint4_b_middle_front_pre: 93

joint1_b_right_front_pre: 126
joint2_b_right_front_pre: 110
joint3_b_right_front_pre: 124
joint4_b_right_front_pre: 99
# ---------------------
joint1_b_left_front: 126
joint2_b_left_front: 110
joint3_b_left_front: 124
joint4_b_left_front: 99

joint1_b_middle_front: 111
joint2_b_middle_front: 111
joint3_b_middle_front: 118
joint4_b_middle_front: 95

joint1_b_right_front: 126
joint2_b_right_front: 115
joint3_b_right_front: 124
joint4_b_right_front: 96
# -------------------------
# -------------------------
joint1_b_left_back: 35
joint2_b_left_back: 115
joint3_b_left_back: 124
joint4_b_left_back: 92

joint1_b_middle_back: 21
joint2_b_middle_back: 109
joint3_b_middle_back: 118
joint4_b_middle_back: 95

joint1_b_right_back: 7
joint2_b_right_back: 115
joint3_b_right_back: 124
joint4_b_right_back: 96
# ---------------------
joint1_b_left_back_pre: 37
joint2_b_left_back_pre: 111
joint3_b_left_back_pre: 124
joint4_b_left_back_pre: 100

joint1_b_middle_back_pre: 21
joint2_b_middle_back_pre: 107
joint3_b_middle_back_pre: 124
joint4_b_middle_back_pre: 93

joint1_b_right_back_pre: 7
joint2_b_right_back_pre: 111
joint3_b_right_back_pre: 124
joint4_b_right_back_pre: 100
# -------------------------
# joint1_b_front: 90
# joint2_b_front: 90
# joint3_b_front: 90
# joint4_b_front: 90

# joint1_b_back: 90
# joint2_b_back: 90
# joint3_b_back: 90
# joint4_b_back: 90
# C 区
joint1_c_left: 90
joint1_c_right: 90
joint2_c_left: 90
joint2_c_right: 90
joint3_c_left: 90
joint3_c_right: 90
joint4_c_left: 90
joint4_c_right: 90

#从下至上
joint1_limiting: [0, 180]     #小：正方向  大：负方向
joint2_limiting: [30, 180]    #da：正方向  大：负方向
joint3_limiting: [40, 160]    #大：正方向  小：负方向
joint4_limiting: [30, 180]    #大：正方向  小：负方向