joint1_a_left: 90.0
joint1_a_right: 90.0
joint2_a_left: 90.0
joint2_a_right: 90.0
joint3_a_left: 90.0
joint3_a_right: 90.0
joint4_a_left: 90.0
joint4_a_right: 90.0

joint1_moving: 90.0
joint1_b_front: 90.0
joint1_b_back: 90.0
joint2_moving: 90.0
joint2_b_front: 90.0
joint2_b_back: 90.0
joint3_moving: 90.0
joint3_b_front: 90.0
joint3_b_back: 90.0
joint4_moving: 90.0
joint4_b_front: 90.0
joint4_b_back: 90.0

joint1_c_left: 90.0
joint1_c_right: 90.0
joint2_limiting: [10.0, 150.0]
joint2_c_left: 90.0
joint2_c_right: 90.0
joint2_limiting: [10.0, 150.0]
joint3_c_left: 90.0
joint3_c_right: 90.0
joint3_limiting: [10.0, 150.0]
joint4_c_left: 90.0
joint4_c_right: 90.0
joint4_limiting: [10.0, 150.0]
