# A 区
# '_a_left' 指的是车在 A 区行驶时车的左边
# '_a_left' 指的是车在 A 区行驶时车的左边
joint1_a_left: 68
joint1_a_right: 45
joint2_a_left: 80
joint2_a_right: 80
joint3_a_left: 65
joint3_a_right: 65
joint4_a_left: 110
joint4_a_right: 110
# B 区
# '_b_front' 指的是车在 A 区行驶时车的前方
# '_b_back' 指的是车在 A 区行驶时车的后方
joint1_moving: 90
joint1_b_front: 90
joint1_b_back: 90
joint2_moving: 90
joint2_b_front: 90
joint2_b_back: 90
joint3_moving: 90
joint3_b_front: 90
joint3_b_back: 90
joint4_moving: 90
joint4_b_front: 90
joint4_b_back: 90
# C 区
joint1_c_left: 90
joint1_c_right: 90
joint2_c_left: 90
joint2_c_right: 90
joint3_c_left: 90
joint3_c_right: 90
joint4_c_left: 90
joint4_c_right: 90

#从下至上
joint1_limiting: [0, 180]     #小：正方向  大：负方向
joint2_limiting: [30, 180]    #da：正方向  大：负方向
joint3_limiting: [40, 160]    #大：正方向  小：负方向
joint4_limiting: [30, 180]    #大：正方向  小：负方向